### ISSUE TITLE
Failing Notebooks: DC, Mag

### ISSUE THREAD

**Issue by lheagy** [ubcgif/gpgLabs#11]
The addition of testing in #10 shows that there are a few notebooks that are currently not running as expected (https://travis-ci.org/ubcgif/gpgLabs/builds/156387428). Here is a list of those that are failing: 
  
- [ ] DC/DCLab.ipynb
- [ ] DC/DCPotentials.ipynb
- [ ] DC/DCwidget.ipynb
- [x] Mag/PlotData.ipynb
- [x] Mag/Prism-TBL.ipynb
- [x] Mag/Prism-TBL_seogi.ipynb
- [x] Mag/Prism-compSphere.ipynb

Some appear to be depending on old SimPEG (or simpegDCIP), and some may be sketch notebooks that are for generating figures/ playing with things. For notebooks that we want to rely on for the course, lets make the dependency on the most recent SimPEG. 

If you would like to keep "sketch" notebooks, please move them to their own folder, and we can ignore these in the testing.

**Comment by lheagy** [comment]
@sgkang : it looks like only the DC ones are failing now. Could you move the broken ones (https://travis-ci.org/ubcgif/gpgLabs) to the "notebooks" repo https://github.com/ubcgif/notebooks while they are under construction and being fixed. We can bring them back here when they are ready to go. 

We will be giving out instructions for students tomorrow for downloading and installing these, so ideally, we should not include broken ones.

**Comment by lheagy** [comment]
Thanks!

**Comment by lheagy** [comment]
There are a series of notebooks still failing:
- [ ] Mag/Library/Earth field and Magnetic data.ipynb
- [ ] Mag/Library/PlotData.ipynb
 in addition to the DC ones mentioned above. 

We will be circulating instructions today on how students can download this repository, so it would be good to ensure that only notebooks that are working are included. 

@sgkang, @fourndo : could you guys take a look and either remove the notebooks that are no longer needed or move them to the https://github.com/ubcgif/notebooks repository where they can be cleaned up and moved back here when ready. 

The travis log is a bit dense, but here is a bit of a breakdown for one of the dc ones that is currently failing

![image](https://cloud.githubusercontent.com/assets/6361812/18592903/e5d7d7a0-7bed-11e6-9055-846786047d06.png)

Thanks! and please let me know if I can help out

**Comment by fourndo** [comment]
Are the mags still showing up? I thought I moved those last night?

**Comment by lheagy** [comment]
It looks like there are still 2 mag ones that are failing in master: https://travis-ci.org/ubcgif/gpgLabs/builds/160358426 - both in the Mag/Library directory

**Comment by fourndo** [comment]
I don't get it. How are these guys tested? Everything seems to fail

**Comment by lheagy** [comment]
Every notebook in the directory is tested. The test walks the repository, looks for anything that ends in `.ipynb` and trys running it. You can do this locally by running `python test_notebooks.py` in the tests folder. 

This uses nbconvert, so when running it locally, it produces html files which I delete (there is some associated output on travis that you can ignore associated with this - see image below) 
![image](https://cloud.githubusercontent.com/assets/6361812/18593696/80ade10e-7bf1-11e6-96d7-e692056879ab.png)

The notebooks that are currently failing are
- ubcgif/gpgLabs/DC/DCLab.ipynb 
![image](https://cloud.githubusercontent.com/assets/6361812/18593807/eff73bf0-7bf1-11e6-834b-468a4712b21e.png)

- ubcgif/gpgLabs/DC/DCPotentials.ipynb
![image](https://cloud.githubusercontent.com/assets/6361812/18593849/21fce7f8-7bf2-11e6-988e-dbae791bdb65.png)

- ubcgif/gpgLabs/DC/DCwidget.ipynb
![image](https://cloud.githubusercontent.com/assets/6361812/18593883/457f1160-7bf2-11e6-9e11-ae71a31fa954.png)

It looks like all of the mag stuff has now been taken care of in #16

**Comment by lheagy** [comment]
Sorry the travis log is so dense! - running it locally is a little more transparent
