### ISSUE TITLE
mag notebooks - failing 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/gpgLabs#14]
The following notebooks are currently failing. See https://travis-ci.org/ubcgif/gpgLabs 
- [x] Mag/Library/Earth field and Magnetic data.ipynb
![image](https://cloud.githubusercontent.com/assets/6361812/18575667/39e97718-7b8f-11e6-8504-95b70fa3159b.png)

- [x] Mag/Library/PlotData.ipynb
![image](https://cloud.githubusercontent.com/assets/6361812/18575688/706e7284-7b8f-11e6-8ecf-dba51c88cf37.png)

Can we move these to the notebooks repo (https://github.com/ubcgif/notebooks) while they are under construction?

**Comment by fourndo** [comment]
Done. There are out,.
