### ISSUE TITLE
EM Lab 8 - numerical error

### ISSUE THREAD

**Issue by sdevriese** [ubcgif/gpgLabs#2]
For Q4, the inclination and declination of the loop is changed to 0, meaning there is no coupling with the primary magnetic field, and Hs is zero. The applet shows a small peak though (numerical error). Can this be fixed? Seogi mentioned this created some confusion last year.

**Comment by sgkang** [comment]
Hi @sdevriese I fixed the code. Have a look. 
While you are playing with notebook, let me know is there a specific thing that you want to change about widget. Compared to last year we have more tricks that we can put on our widget. 

Thanks.
